; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
description = "пример выполнения из flash и из sram"

[env]
platform = ststm32
board = nucleo_h745zi_q
framework = cmsis
build_flags = -std=c11 -Wall -Wextra -D CORE_CM7 -D PWR_DIRECT_SMPS_SUPPLY -D HSE_VALUE=8000000
board_build.cmsis.startup_file = broken_path
board_build.cmsis.system_file = broken_path
monitor_speed = 115200
test_speed = 115200
test_filter = target/*
test_framework = custom ; использовать test_custom_runner.py в папке test
check_tool = cppcheck
check_flags = cppcheck:--enable=all --suppress=unusedFunction  
check_src_filters = +<src/app/*.c>
build_type = debug
debug_init_cmds = target extended-remote $DEBUG_PORT
                  $LOAD_CMDS 
                  $INIT_BREAK


[env:blinker_flash]
build_src_filter = +<$PROJECT_DIR/system/*>
                   +<blinker/blinker2.c>
board_build.ldscript = $PROJECT_DIR/system/h745cm7_flash_app.ld

[env:blinker_ram] ; new target
build_src_filter =  +<blinker/blinker.c> +<$PROJECT_DIR/system/*>                
board_build.ldscript = $PROJECT_DIR/system/stm32h745xx_sram1_CM7.ld
build_flags = ${env.build_flags} -DVECT_TAB_SRAM

[env:bootloader]
build_src_filter = +<bootloader/bootloader_main.c> +<$PROJECT_DIR/system/*>  
board_build.ldscript = $PROJECT_DIR/system/h745cm7_flash.ld
check_src_filters = +<src/bootloader/bootloader_main.c>
